apiVersion: v1
kind: Service
metadata:
  name: wso2am-gw
  namespace: wso2am
spec:
  selector:
    app: wso2am-gw
  ports:
    - name: portal
      port: 9443
      targetPort: 9443
    - name: gateway-http
      port: 8280
      targetPort: 8280
    - name: gateway-https
      port: 8243
      targetPort: 8243
