apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2am-cp-pv-volume
  namespace: wso2am
spec:
  storageClassName: apim-cp
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/contolplaneconfig"