apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2am-cp
  namespace: wso2am
  labels:
    app: wso2am-cp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wso2am-cp
  template:
    metadata:
      labels:
        app: wso2am-cp
    spec:
      containers:
      - name: wso2am-cp
        image: wso2/wso2am:4.1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
         - mountPath: "/home/wso2carbon/wso2-config-volume"
           name: wso2am-cp-storage
      volumes:
      - name: wso2am-cp-storage
        persistentVolumeClaim:
         claimName: wso2am-cp-pv-claim