apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2am-cp-pvc
  namespace: wso2am
spec:
  storageClassName: apim-cp
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
