apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2am-gw-pv-volume
  namespace: wso2am
spec:
  storageClassName: apim-gw
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/gatewayconfig/"
