apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2am-gw-pv-claim
  namespace: wso2am
spec:
  storageClassName: apim-gw
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
